
spring:
  datasource:
    url: jdbc:h2:mem:paymentdb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
  h2:
    console.enabled: true
server:
  port: 8081
twilio:
  account_sid: AC3ff9c3963b13c46f572156ec99df94c6
  auth_token: 3a951ef186a6c5f45af9134a71caf062
  trial_number: +16074007628